#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/handout-hackertours-by-vincent:latest@sha256:16021bc112c0ae749355d5d6789fb3ef22ae2b8b5f3b5891308e1b09736e0f79
    restart: on-failure:5
    environment:
      - PASSPHRASE=${PASSPHRASE}
      - GEOAPIFY_API_KEY=${GEOAPIFY_API_KEY}
    ports:
      - "3002:3000"

  gotenberg:
    image: gotenberg/gotenberg:8
