#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/handout-hackertours-by-vincent:latest@sha256:2523da1beddbddfa1f413e2564c1cd182d5f607ea1270619dd3b11786ac5cd53
    restart: on-failure:5
    environment:
      - PASSPHRASE=${PASSPHRASE}
      - GEOAPIFY_API_KEY=${GEOAPIFY_API_KEY}
    ports:
      - "3002:3000"

  gotenberg:
    image: gotenberg/gotenberg:8
