#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/handout-hackertours-by-vincent:latest@sha256:dedd59c4925c1e4248c23c560858723feb8210fd1e88f217e41d9a1de743a756
    restart: on-failure:5
    environment:
      - PASSPHRASE=${PASSPHRASE}
      - GEOAPIFY_API_KEY=${GEOAPIFY_API_KEY}
    ports:
      - "3002:3000"

  gotenberg:
    image: gotenberg/gotenberg:8
